version: '2'
services:
  auth_service:
    build: ./Dockerfile
    ports:
      - 3000:3000
    command: python auth_service/api.py
  data_service:
    build: ./Dockerfile
    ports:
      - 3001:3001
    command: python data_service/api.py
  apache2:
    build: ./apache.Dockerfile
    ports:
      - 80:80
    command: service apache2 restart