#!/bin/bash
virtualenv -p python3 env \
source env/bin/activate \
pip install -r auth_service/requirements.txt \
export MONGODB=mongodb://localhost:27017/ \
python auth_service/api.py & \
python data_service/api.py & \